prefix p: <http://TI.com>
prefix d: <http://TI.com/ns/data#>

SELECT  ?Matkul ?jenisMatkul ?dosenPengajar ?jumlahSks ?semester ?deskripsi ?syaratLulus
WHERE
    { 
        ?s  d:namaMatkul ?Matkul ;
            d:jenisMatkul ?jenisMatkul;
            d:dosenPengajar ?dosenPengajar;
            d:jumlahSks ?jumlahSks;
            d:semester ?semester;
            d:tentangMatkul ?lorem.

        ?lorem  d:deskripsi      ?deskripsi;
                d:syaratLulus    ?syaratLulus.
                      
    }